#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/CoinTrack.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ArzYab                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Track your crypto portfolio and get real-time updates on your investments.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nabi Rahmani                              
your_link                                 :                      
your_city                                 :                                
email_address                             : codewithnabi@gmail.com
linkedin_username                         : muhammad-nabi-rahmani-%F0%9F%87%B5%F0%9F%87%B8-8945b21ba                                          
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : nabirahmani_dev
github_username                           : Nabi-Rahmani 
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Real-Time Crypto Tracking
    description                           : Monitor live cryptocurrency prices with automatic updates. Never miss a market movement with instant price refreshes.
    fontawesome_icon_name                 : chart-line
    
  - title                                 : Smart Price Alerts
    description                           : Set custom price targets and receive push notifications when your coins hit the perfect buy or sell point.
    fontawesome_icon_name                 : bell

  - title                                 : Lightning-Fast Search
    description                           : Find any cryptocurrency instantly with our advanced search. Access hundreds of coins with real-time results.
    fontawesome_icon_name                 : search

  - title                                 : Beautiful Modern Design
    description                           : Clean, intuitive interface with dark/light themes. Designed for effortless navigation and comfortable viewing.
    fontawesome_icon_name                 : palette

  - title                                 : Works Everywhere
    description                           : Available on iOS, Android, Web, macOS, Windows, and Linux. Your crypto data syncs across all devices.
    fontawesome_icon_name                 : globe
  
  - title                                 : Lightning Performance
    description                           : Smart caching and offline support ensure blazing-fast load times, even with poor internet connection.
    fontawesome_icon_name                 : bolt

  - title                                 : Personalized Experience
    description                           : Customize alerts, themes, and notifications. Track your favorite coins with personalized watchlists.
    fontawesome_icon_name                 : user-cog

  - title                                 : Secure & Private
    description                           : Your data is protected with Firebase security. Local storage keeps your preferences private and secure.
    fontawesome_icon_name                 : shield-alt

  - title                                 : Market Intelligence
    description                           : View price history, market cap, trading volume, and trending coins. Make informed investment decisions.
    fontawesome_icon_name                 : brain

  - title                                 : Never Miss Opportunities
    description                           : Advanced notification system with Firebase Cloud Messaging. Get alerted the moment your target price hits.
    fontawesome_icon_name                 : bullseye

  - title                                 : Offline Ready
    description                           : Access your data even without internet. Smart caching ensures your crypto info is always available.
    fontawesome_icon_name                 : wifi

  - title                                 : Easy Customization
    description                           : Switch between themes, adjust notification settings, and personalize your experience with simple toggles.
    fontawesome_icon_name                 : sliders-h

  - title                                 : Professional Architecture
    description                           : Built with clean architecture and industry best practices. Reliable, scalable, and maintainable codebase.
    fontawesome_icon_name                 : code

  - title                                 : Auto-Sync Alerts
    description                           : Your price alerts automatically sync across all devices. Set once, get notified everywhere.
    fontawesome_icon_name                 : sync

  - title                                 : Comprehensive Data
    description                           : Access detailed cryptocurrency information including rankings, market trends, and price movements.
    fontawesome_icon_name                 : database



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#1a1a2e"
cover_overlay_transparency                : 0.4

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
